# Generated by Django 5.0.7 on 2024-08-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varition',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
