# Generated by Django 5.0.7 on 2024-08-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_varition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varition',
            new_name='variation',
        ),
    ]
