# Generated by Django 5.0.7 on 2024-08-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_varition_cartitem_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variation',
            new_name='variations',
        ),
    ]
